### ISSUE TITLE
Enable LSI for better indexing

### ISSUE THREAD

**Issue by alias1** [alias1/devalias.net#1]
Will need jekyll/classifier-reborn#14 to be fixed

Ref: http://stackoverflow.com/questions/30038899/jekyll-build-stuck-in-rebuilding-index-stage

**Comment by alias1** [comment]
Based on [this post](http://footle.org/2014/11/06/speeding-up-jekylls-lsi/), runs in ~6sec now.

**Comment by i2000s** [comment]
Echo up, I am still experiencing this problem now. It stuck at the rebuilding index stage all the time. The only way seems to me to avoid this problem is to disable LSI, but it is obviously not my favourite thing to do. Below are some error codes, I am not sure if this is related:

If I run bundle update:
```
qxd@QC3-ubuntu2:/media/D/SoftwareRep/GitHub/i2000s.github.io$ bundle updateFetching https://github.com/jekyll/classifier-reborn
error: cannot open .git/FETCH_HEAD: Permission denied

Retrying git fetch --force --quiet --tags "/home/qxd/.bundler/cache/git/classifier-reborn-b40019fc26385fa3bb52b56e839dcea45d8000ad" due to error (2/4): Bundler::Source::Git::GitCommandError Git error: command `git fetch --force --quiet --tags "/home/qxd/.bundler/cache/git/classifier-reborn-b40019fc26385fa3bb52b56e839dcea45d8000ad"` in directory /usr/local/lib/ruby/gems/2.1.0/bundler/gems/classifier-reborn-014881c61070 has failed.
If this error persists you could try removing the cache directory '/home/qxd/.bundler/cache/git/classifier-reborn-b40019fc26385fa3bb52b56e839dcea45d8000ad'
error: cannot open .git/FETCH_HEAD: Permission denied

Retrying git fetch --force --quiet --tags "/home/qxd/.bundler/cache/git/classifier-reborn-b40019fc26385fa3bb52b56e839dcea45d8000ad" due to error (3/4): Bundler::Source::Git::GitCommandError Git error: command `git fetch --force --quiet --tags "/home/qxd/.bundler/cache/git/classifier-reborn-b40019fc26385fa3bb52b56e839dcea45d8000ad"` in directory /usr/local/lib/ruby/gems/2.1.0/bundler/gems/classifier-reborn-014881c61070 has failed.
If this error persists you could try removing the cache directory '/home/qxd/.bundler/cache/git/classifier-reborn-b40019fc26385fa3bb52b56e839dcea45d8000ad'
error: cannot open .git/FETCH_HEAD: Permission denied

Retrying git fetch --force --quiet --tags "/home/qxd/.bundler/cache/git/classifier-reborn-b40019fc26385fa3bb52b56e839dcea45d8000ad" due to error (4/4): Bundler::Source::Git::GitCommandError Git error: command `git fetch --force --quiet --tags "/home/qxd/.bundler/cache/git/classifier-reborn-b40019fc26385fa3bb52b56e839dcea45d8000ad"` in directory /usr/local/lib/ruby/gems/2.1.0/bundler/gems/classifier-reborn-014881c61070 has failed.
If this error persists you could try removing the cache directory '/home/qxd/.bundler/cache/git/classifier-reborn-b40019fc26385fa3bb52b56e839dcea45d8000ad'
error: cannot open .git/FETCH_HEAD: Permission denied

Git error: command `git fetch --force --quiet --tags
"/home/qxd/.bundler/cache/git/classifier-reborn-b40019fc26385fa3bb52b56e839dcea45d8000ad"`
in directory
/usr/local/lib/ruby/gems/2.1.0/bundler/gems/classifier-reborn-014881c61070 has
failed.
If this error persists you could try removing the cache directory
'/home/qxd/.bundler/cache/git/classifier-reborn-b40019fc26385fa3bb52b56e839dcea45d8000ad'
```
When run `bundle exec jekyll serve` and give a ctr-C, it gives
```
Rebuilding index... 

^C/usr/local/lib/ruby/2.1.0/matrix.rb:823:in `block (3 levels) in *': Interrupt
	from /usr/local/lib/ruby/2.1.0/matrix.rb:822:in `each'
	from /usr/local/lib/ruby/2.1.0/matrix.rb:822:in `inject'
	from /usr/local/lib/ruby/2.1.0/matrix.rb:822:in `block (2 levels) in *'
	from /usr/local/lib/ruby/2.1.0/matrix.rb:821:in `initialize'
	from /usr/local/lib/ruby/2.1.0/matrix.rb:821:in `new'
	from /usr/local/lib/ruby/2.1.0/matrix.rb:821:in `block in *'
	from /usr/local/lib/ruby/2.1.0/matrix.rb:820:in `initialize'
	from /usr/local/lib/ruby/2.1.0/matrix.rb:820:in `new'
	from /usr/local/lib/ruby/2.1.0/matrix.rb:820:in `*'
	from /usr/local/lib/ruby/gems/2.1.0/bundler/gems/classifier-reborn-014881c61070/lib/classifier-reborn/extensions/vector.rb:42:in `block (3 levels) in SV_decomp'
	from /usr/local/lib/ruby/gems/2.1.0/bundler/gems/classifier-reborn-014881c61070/lib/classifier-reborn/extensions/vector.rb:31:in `each'
	from /usr/local/lib/ruby/gems/2.1.0/bundler/gems/classifier-reborn-014881c61070/lib/classifier-reborn/extensions/vector.rb:31:in `block (2 levels) in SV_decomp'
	from /usr/local/lib/ruby/gems/2.1.0/bundler/gems/classifier-reborn-014881c61070/lib/classifier-reborn/extensions/vector.rb:30:in `each'
	from /usr/local/lib/ruby/gems/2.1.0/bundler/gems/classifier-reborn-014881c61070/lib/classifier-reborn/extensions/vector.rb:30:in `block in SV_decomp'
	from /usr/local/lib/ruby/gems/2.1.0/bundler/gems/classifier-reborn-014881c61070/lib/classifier-reborn/extensions/vector.rb:28:in `loop'
	from /usr/local/lib/ruby/gems/2.1.0/bundler/gems/classifier-reborn-014881c61070/lib/classifier-reborn/extensions/vector.rb:28:in `SV_decomp'
	from /usr/local/lib/ruby/gems/2.1.0/bundler/gems/classifier-reborn-014881c61070/lib/classifier-reborn/lsi.rb:292:in `build_reduced_matrix'
	from /usr/local/lib/ruby/gems/2.1.0/bundler/gems/classifier-reborn-014881c61070/lib/classifier-reborn/lsi.rb:138:in `build_index'
	from /usr/local/lib/ruby/gems/2.1.0/gems/jekyll-2.5.3/lib/jekyll/related_posts.rb:38:in `build_index'
	from /usr/local/lib/ruby/gems/2.1.0/gems/jekyll-2.5.3/lib/jekyll/related_posts.rb:20:in `build'
	from /usr/local/lib/ruby/gems/2.1.0/gems/jekyll-2.5.3/lib/jekyll/post.rb:241:in `related_posts'
	from /usr/local/lib/ruby/gems/2.1.0/gems/jekyll-2.5.3/lib/jekyll/post.rb:253:in `render'
	from /usr/local/lib/ruby/gems/2.1.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:298:in `block in render'
	from /usr/local/lib/ruby/gems/2.1.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:297:in `each'
	from /usr/local/lib/ruby/gems/2.1.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:297:in `render'
	from /usr/local/lib/ruby/gems/2.1.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:51:in `process'
	from /usr/local/lib/ruby/gems/2.1.0/gems/jekyll-2.5.3/lib/jekyll/command.rb:28:in `process_site'
	from /usr/local/lib/ruby/gems/2.1.0/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:56:in `build'
	from /usr/local/lib/ruby/gems/2.1.0/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:34:in `process'
	from /usr/local/lib/ruby/gems/2.1.0/gems/jekyll-2.5.3/lib/jekyll/commands/serve.rb:26:in `block (2 levels) in init_with_program'
	from /usr/local/lib/ruby/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
	from /usr/local/lib/ruby/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
	from /usr/local/lib/ruby/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
	from /usr/local/lib/ruby/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
	from /usr/local/lib/ruby/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
	from /usr/local/lib/ruby/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
	from /usr/local/lib/ruby/gems/2.1.0/gems/jekyll-2.5.3/bin/jekyll:20:in `<top (required)>'
	from /usr/local/bin/jekyll:23:in `load'
	from /usr/local/bin/jekyll:23:in `<main>'
```
I have installed `gsl-bin` and libgsl0-dev`.
